import { randomBytes } from "node:crypto";
import type { RelayerConfig } from "./config.js";
import { TransferDatabase } from "./database.js";
import { buildBurnIntent, burnIntentHash } from "./onchain.js";
import type { BurnIntentAuthorization, ChainLog, EventSource, EventType, GatewayClient, Logger, LogProvider, SettlementExecutor, SettlementInput, SettlementRow } from "./types.js";
const retryDelaySeconds=[30,120,600,1800] as const;
export class Relayer {
  private readonly inFlight=new Set<string>(); private readonly escrows=new Map<string,number>(); private retryTimer:NodeJS.Timeout|undefined; private active=false; private prepared=false;
  public constructor(public readonly config:RelayerConfig,public readonly database:TransferDatabase,private readonly provider:LogProvider,private readonly eventSource:EventSource,private readonly gateway:GatewayClient,private readonly executor:SettlementExecutor,private readonly logger:Logger,private readonly now=()=>Math.floor(Date.now()/1000)){}
  public get listening(){return this.active;}
  public async initialize(){
    await this.prepare();
    const historicalTo=process.env.SKIP_HISTORICAL_SWEEP==="true"?await this.provider.getBlockNumber():await this.historicalSweep();
    this.eventSource.subscribe(this.config.factoryEventTopic,l=>this.handleFactoryLog(l));
    for(const topic of Object.values(this.config.eventTopics))this.eventSource.subscribe(topic,l=>void this.handleLog(l));
    if(this.eventSource.start)await this.eventSource.start(historicalTo);
    this.active=true;
    this.retryTimer=setInterval(()=>void this.processDueRetries(),10000);this.retryTimer.unref();
    this.logger.info("Relayer initialized",{factoryAddress:this.config.factoryAddress,escrowCount:this.escrows.size,historicalSweep:process.env.SKIP_HISTORICAL_SWEEP==="true"?"skipped":"completed"});
  }
  public async prepare(){
    if(this.prepared)return;
    await this.validateContractWithRetry();
    this.database.migrate();
    await this.resumeNonTerminal();
    this.prepared=true;
  }
  private async validateContractWithRetry(){const backoffMs=[0,2000,5000,15000,30000];let lastError:unknown;for(let i=0;i<backoffMs.length;i++){if(backoffMs[i]>0)await new Promise<void>(resolve=>setTimeout(resolve,backoffMs[i]));const attempt=i+1;this.logger.info("Startup validation attempt",{attempt,maxAttempts:backoffMs.length});try{const code=await this.provider.getCode(this.config.factoryAddress);if(code==="0x")throw new Error(`No deployed factory code at ${this.config.factoryAddress}`);this.logger.info("Startup validation succeeded",{attempt});return;}catch(error){lastError=error;if(attempt<backoffMs.length)this.logger.warn("Startup validation failed; retrying",{attempt,nextAttempt:attempt+1,error:String(error)});}}throw lastError;}
  public stop(){this.active=false;this.eventSource.unsubscribe();if(this.retryTimer)clearInterval(this.retryTimer);this.retryTimer=undefined;}
  public async historicalSweep(){
    const to=await this.rpcRetry("historical block number",()=>this.provider.getBlockNumber());
    const factoryTopics=[[this.config.factoryEventTopic]];
    const chunkSize=500;
    for(let from=this.config.factoryDeploymentBlock;from<=to;from+=chunkSize){const end=Math.min(from+chunkSize-1,to);const logs=await this.rpcRetry(`factory logs ${from}-${end}`,()=>this.provider.getLogs({address:this.config.factoryAddress,fromBlock:from,toBlock:end,topics:factoryTopics}));for(const l of logs)this.handleFactoryLog(l);}
    const escrowTopics=[Object.values(this.config.eventTopics)];
    for(const [address,createdBlock] of this.escrows){for(let from=createdBlock;from<=to;from+=chunkSize){const end=Math.min(from+chunkSize-1,to);const logs=await this.rpcRetry(`historical logs ${address} ${from}-${end}`,()=>this.provider.getLogs({address,fromBlock:from,toBlock:end,topics:escrowTopics}));for(const l of logs)await this.handleLog(l);}}
    return to;
  }
  private handleFactoryLog(log:ChainLog):void{if(log.removed)return;try{const d=this.config.factoryAbi.decodeEventLog("AgreementCreated",log.data,log.topics);const address=String(d[1]).toLowerCase();if(!this.escrows.has(address)){this.escrows.set(address,log.blockNumber);this.eventSource.addAddress(address);this.logger.info("Escrow discovered",{agreementId:String(d[0]),escrowAddress:address});}}catch(error){this.logger.error("Unable to decode agreement-created event",{error:String(error)});}}
  private async rpcRetry<T>(label:string,operation:()=>Promise<T>):Promise<T>{let lastError:unknown;for(const delayMs of [0,2000,5000]){if(delayMs)await new Promise<void>(resolve=>setTimeout(resolve,delayMs));try{return await operation();}catch(error){lastError=error;this.logger.warn("RPC request failed; retrying",{label,attempt:delayMs===0?1:delayMs===2000?2:3,error:String(error)});}}throw lastError;}
  public async handleLog(log:ChainLog){const input=this.decodeSettlement(log);if(!input)return;if(log.removed){this.logger.warn("reorg detected",{settlementKey:input.settlementKey});return;}if(!this.database.insert(input,this.now()))return;await this.initiateSettlement(input.settlementKey);}
  public async resumeNonTerminal(){for(const row of this.database.nonTerminal()){if(row.status==="AUTHORIZED"||row.status==="MINTING"||row.nextRetryAt===null||row.nextRetryAt<=this.now())await this.initiateSettlement(row.settlementKey);}}
  public async processDueRetries(){for(const row of this.database.due(this.now()))await this.initiateSettlement(row.settlementKey);}
  public async initiateSettlement(key:string){if(this.inFlight.has(key))return;const row=this.database.get(key);if(!row||this.database.isTerminal(row.status))return;this.inFlight.add(key);try{await this.submit(row);}finally{this.inFlight.delete(key);}}
  private async submit(row:SettlementRow){const now=this.now();const attempt=row.attemptCount+1;let gatewaySubmissionAttempted=false;this.database.markAttempt(row.settlementKey,attempt,now);try{
    if(row.status==="MINTING" && row.attestation && row.operatorSignature){const minted=await this.executor.mint({attestation:row.attestation,signature:row.operatorSignature});this.database.update(row.settlementKey,{status:"MINTED",mintTxHash:minted.mintTxHash},this.now());return;}
    if(row.gatewayTransferId && this.gateway.getTransfer){if(await this.recoverGatewayTransfer(row,attempt,now))return;return;}
    let request=row.burnIntentJson?JSON.parse(row.burnIntentJson):undefined;
    if(!request){const amount=parseUsdc(row.amount);const maxFee=3500n;if(this.provider.getAvailableBalance){const available=await this.provider.getAvailableBalance("0x3600000000000000000000000000000000000000",row.escrowAddress);if(available<amount+maxFee)throw new Error(`Insufficient Gateway Wallet balance for ${row.settlementKey}: available ${available}, required ${amount+maxFee}`);}const auth:BurnIntentAuthorization={settlementIndex:row.milestoneIndex===null?2n**256n-1n:BigInt(row.milestoneIndex),maxBlockHeight:2n**256n-1n,maxFee,salt:"0x"+randomBytes(32).toString("hex"),recipient:row.recipient,amount,burnIntentRequest:undefined as never};request=buildBurnIntent(auth,{contractAddress:row.escrowAddress,gatewayWalletAddress:this.config.gatewayWalletAddress,gatewayMinterAddress:this.config.gatewayMinterAddress});auth.burnIntentRequest=request;const authorized=await this.executor.authorize(auth,row.escrowAddress);this.database.update(row.settlementKey,{status:"AUTHORIZED",authorizationTxHash:authorized.authorizationTxHash,burnIntentHash:authorized.burnIntentHash,burnIntentJson:JSON.stringify(request)},now);row={...row,status:"AUTHORIZED",authorizationTxHash:authorized.authorizationTxHash,burnIntentHash:authorized.burnIntentHash,burnIntentJson:JSON.stringify(request)};}
    gatewaySubmissionAttempted=true;const result=await this.gateway.submit({burnIntent:request,signature:"0x00",contractSigner:true});const body=stringify(result.body);if(result.status<200||result.status>=300){if(result.status>=400&&result.status<500)this.database.update(row.settlementKey,{status:"PERMANENT_FAILURE",gatewayResponse:body},now);else this.retry(row,attempt,body,`Gateway returned HTTP ${result.status}`,now);return;}
    const transferId=extractTransferId(result.body);if(transferId){this.database.update(row.settlementKey,{gatewayTransferId:transferId,gatewayResponse:body},now);row={...row,gatewayTransferId:transferId,gatewayResponse:body};}
    let att=extractAttestation(result.body);if(!att&&transferId&&this.gateway.getTransfer){const recovered=await this.gateway.getTransfer(transferId);const recoveredBody=stringify(recovered.body);att=extractAttestation(recovered.body);if(!att){this.retry(row,attempt,recoveredBody,"Gateway attestation unavailable; retrying recovery without resubmission",now);return;}this.database.update(row.settlementKey,{gatewayResponse:recoveredBody},now);}
    if(!att){this.database.update(row.settlementKey,{status:"FAILED",gatewayResponse:body,nextRetryAt:null},now);this.logger.error("Gateway submission outcome unknown; manual recovery required",{settlementKey:row.settlementKey});return;}this.database.update(row.settlementKey,{status:"MINTING",gatewayResponse:body,gatewayTransferId:att.id,attestation:att.payload,operatorSignature:att.signature},now);const minted=await this.executor.mint({attestation:att.payload,signature:att.signature});this.database.update(row.settlementKey,{status:"MINTED",mintTxHash:minted.mintTxHash},this.now());this.logger.info("Gateway settlement minted",{settlementKey:row.settlementKey,mintTxHash:minted.mintTxHash});
  }catch(e){if(gatewaySubmissionAttempted&&!row.gatewayTransferId){const response=stringifyError(e);this.database.update(row.settlementKey,{status:"FAILED",gatewayResponse:response,nextRetryAt:null},now);this.logger.error("Gateway submission outcome unknown; manual recovery required",{settlementKey:row.settlementKey});return;}this.retry(row,attempt,stringifyError(e),"Settlement attempt failed",now);}}
  private async recoverGatewayTransfer(row:SettlementRow,attempt:number,now:number):Promise<boolean>{const result=await this.gateway.getTransfer!(row.gatewayTransferId!);const body=stringify(result.body);const att=extractAttestation(result.body);if(att){this.database.update(row.settlementKey,{status:"MINTING",gatewayResponse:body,attestation:att.payload,operatorSignature:att.signature},now);const minted=await this.executor.mint({attestation:att.payload,signature:att.signature});this.database.update(row.settlementKey,{status:"MINTED",mintTxHash:minted.mintTxHash},this.now());this.logger.info("Gateway settlement minted",{settlementKey:row.settlementKey,mintTxHash:minted.mintTxHash});return true;}if(result.status>=400&&result.status<500){this.database.update(row.settlementKey,{status:"FAILED",gatewayResponse:body,nextRetryAt:null},now);this.logger.error("Gateway transfer recovery failed",{settlementKey:row.settlementKey,transferId:row.gatewayTransferId});return true;}this.retry(row,attempt,body,"Gateway attestation unavailable; retrying recovery without resubmission",now);return false;}
  private retry(row:SettlementRow,attempt:number,response:string,reason:string,now:number){if(attempt>=5){this.database.update(row.settlementKey,{status:"FAILED",gatewayResponse:response,nextRetryAt:null},now);this.logger.error("Settlement exhausted retry budget",{settlementKey:row.settlementKey,reason});return;}const delay=retryDelaySeconds[attempt-1];this.database.update(row.settlementKey,{status:"RETRYING",gatewayResponse:response,nextRetryAt:now+delay},now);this.logger.warn("Settlement scheduled for retry",{settlementKey:row.settlementKey,nextRetryAt:now+delay,reason});}
  private decodeSettlement(log:ChainLog):SettlementInput|undefined{const topic=log.topics[0]?.toLowerCase();const pair=(Object.entries(this.config.eventTopics) as Array<[EventType,string]>).find(([,v])=>v.toLowerCase()===topic);if(!pair)return;try{const [eventType]=pair;const d=this.config.contractAbi.decodeEventLog(eventType,log.data,log.topics);const reclaimed=eventType==="FundsReclaimed";const index=reclaimed?null:Number(d[0]);const off=reclaimed?0:1;const recipient=String(d[off]);const amount=formatUsdc(BigInt(d[off+1]));const settlementKey=`${log.address}:${log.transactionHash}:${log.logIndex??0}:${eventType}:${index??"reclaim"}`;return{settlementKey,escrowAddress:log.address,eventType,milestoneIndex:index,recipient,amount,txHash:log.transactionHash,blockNumber:log.blockNumber,logIndex:log.logIndex??null};}catch(e){this.logger.error("Unable to decode fund-movement event",{error:String(e)});return;}}
}
function parseUsdc(s:string){const [a,b=""] = s.split(".");return BigInt(a)*1000000n+BigInt((b+"000000").slice(0,6));}
function formatUsdc(a:bigint){return `${a/1000000n}.${(a%1000000n).toString().padStart(6,"0")}`;}
function stringify(v:unknown){try{return JSON.stringify(v)??"null";}catch{return String(v);}}
function stringifyError(e:unknown){return stringify(e instanceof Error?{name:e.name,message:e.message}:e);}
function extractTransferId(body:unknown):string|undefined{const b=body as any;const id=b?.transferId??b?.id??b?.data?.transferId??b?.transfer?.transferId;return typeof id==="string"&&id? id:undefined;}
function extractAttestation(body:unknown):{id:string|null;payload:string;signature:string}|undefined{const b=body as any;const nested=typeof b?.attestation==="object"?b.attestation:(b?.data?.attestation??b?.transfer?.attestation);const payload=typeof b?.attestation==="string"?b.attestation:(nested?.payload??nested?.attestationPayload??nested?.encoded);const signature=typeof b?.signature==="string"?b.signature:(nested?.signature??b?.data?.signature??b?.transfer?.signature);if(typeof payload!=="string"||typeof signature!=="string")return;return{id:extractTransferId(body)??null,payload,signature};}
