import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createServer } from "node:http";
import { test } from "node:test";
import { Interface } from "ethers";
import { loadConfig, type RelayerConfig } from "../src/config.js";
import { TransferDatabase } from "../src/database.js";
import { CircleGatewayClient } from "../src/gateway.js";
import { Relayer } from "../src/relayer.js";
import { EthersPollingEventSource } from "../src/event-source.js";
import { settlementSalt } from "../src/onchain.js";
import type { ChainLog, EventSource, GatewayClient, GatewayResult, Logger, LogProvider, SettlementExecutor } from "../src/types.js";

const escrow="0x1111111111111111111111111111111111111111", recipient="0x2222222222222222222222222222222222222222";
const abi=new Interface(["event MilestoneReleased(uint256 index,address recipient,uint256 amount)","event FundsReclaimed(address recipient,uint256 amount)"]);
const factoryAbi=new Interface(["event AgreementCreated(bytes32 indexed agreementId,address indexed escrow,address indexed buyer,address seller,address arbitrator,uint256 totalUSDC)"]);
const topics={MilestoneReleased:abi.getEvent("MilestoneReleased")!.topicHash,MilestoneArbitrated:abi.getEvent("MilestoneReleased")!.topicHash,ArbitrationForced:abi.getEvent("MilestoneReleased")!.topicHash,FundsReclaimed:abi.getEvent("FundsReclaimed")!.topicHash};
class Provider implements LogProvider { constructor(private logs:ChainLog[]=[]){ } async getBlockNumber(){return 10;} async getCode(){return "0x6000";} async getLogs(){return this.logs;} }
class Source implements EventSource { private fn?: (l:ChainLog)=>void; subscribe(_t:string,fn:(l:ChainLog)=>void){this.fn=fn;} addAddress(){} unsubscribe(){} emit(l:ChainLog){this.fn?.(l);} }
class Log implements Logger { debug(){} info(){} warn(){} error(){} }
class Gateway implements GatewayClient { requests:any[]=[]; getRequests=0; async submit(r:any):Promise<GatewayResult>{this.requests.push(r);return {status:200,body:{id:"t1",attestation:{payload:"0xabc",signature:"0xsig"}}};} async getTransfer(id:string):Promise<GatewayResult>{this.getRequests++;return {status:200,body:{id,attestation:{payload:"0xabc",signature:"0xsig"}}};} }
class UnknownThenGateway implements GatewayClient { requests:any[]=[]; attempt=0; async submit(r:any):Promise<GatewayResult>{this.requests.push(JSON.parse(JSON.stringify(r)));this.attempt++;return this.attempt===1?{status:500,body:{error:"temporary upstream failure"}}:{status:200,body:{id:"t-recovered",attestation:{payload:"0xrecovered",signature:"0xrecovered"}}};} async getTransfer(id:string):Promise<GatewayResult>{return {status:200,body:{id,attestation:{payload:"0xrecovered",signature:"0xrecovered"}}};} }
class ErrorWithTransferIdGateway implements GatewayClient { requests:any[]=[]; getRequests=0; async submit(r:any):Promise<GatewayResult>{this.requests.push(JSON.parse(JSON.stringify(r)));return {status:500,body:{id:"t-known",error:"temporary upstream failure"}};} async getTransfer(id:string):Promise<GatewayResult>{this.getRequests++;return {status:200,body:{id,attestation:{payload:"0xrecovered",signature:"0xrecovered"}}};} }
class FourHundredWithTransferIdGateway implements GatewayClient { requests:any[]=[]; getRequests=0; async submit(r:any):Promise<GatewayResult>{this.requests.push(JSON.parse(JSON.stringify(r)));return {status:400,body:{id:"t-400",error:"request rejected after transfer creation"}};} async getTransfer(id:string):Promise<GatewayResult>{this.getRequests++;return {status:200,body:{id,attestation:{payload:"0xrecovered400",signature:"0xrecovered400"}}};} }
class PendingThenGateway implements GatewayClient { requests:any[]=[]; getRequests=0; statusChecks=0; async submit(r:any):Promise<GatewayResult>{this.requests.push(JSON.parse(JSON.stringify(r)));return {status:201,body:{id:"t-pending",fees:{total:"0.0035"}}};} async getTransfer(id:string):Promise<GatewayResult>{this.getRequests++;this.statusChecks++;return this.statusChecks===1?{status:200,body:{id,status:"pending"}}:{status:200,body:{id,attestation:{payload:"0xpending",signature:"0xpending"}}};} }
class BlockingGateway implements GatewayClient { requests:any[]=[]; release!:()=>void; submitted=new Promise<void>(resolve=>{this.release=resolve;}); async submit(r:any):Promise<GatewayResult>{this.requests.push(r);await this.submitted;return {status:200,body:{id:"t-blocked",attestation:{payload:"0xblocked",signature:"0xblocked"}}};} async getTransfer(id:string):Promise<GatewayResult>{return {status:200,body:{id,attestation:{payload:"0xblocked",signature:"0xblocked"}}};} }
class Executor implements SettlementExecutor { auths:any[]=[]; mints:any[]=[]; failMintOnce=false; async authorize(i:any,_address:string){this.auths.push(i);return {burnIntentHash:"0x"+"aa".repeat(32),authorizationTxHash:"0x"+"bb".repeat(32)};} async mint(i:any){this.mints.push(i);if(this.failMintOnce){this.failMintOnce=false;throw new Error("unknown mint submission outcome");}return {mintTxHash:"0x"+"cc".repeat(32)};} }
function cfg():RelayerConfig{return {contractAddress:escrow,contractAbi:abi,factoryAddress:"0x3333333333333333333333333333333333333333",factoryAbi,factoryEventTopic:factoryAbi.getEvent("AgreementCreated")!.topicHash,factoryDeploymentBlock:1,eventTopics:topics,onchainEventTopics:{ContractCommitted:"0x"+"01".repeat(32),ContractActivated:"0x"+"02".repeat(32),ContractFinalized:"0x"+"03".repeat(32),CommitmentAbandoned:"0x"+"04".repeat(32)},gatewayWalletAddress:"0x3333333333333333333333333333333333333333",gatewayMinterAddress:"0x4444444444444444444444444444444444444444",deploymentBlock:1,arcRpcUrl:"http://localhost:1",gatewayApiBaseUrl:"http://localhost:1",relayerPrivateKey:"0x"+"11".repeat(32),relayerPort:0,sqlitePath:":memory:"};}
function log():ChainLog {const e=abi.encodeEventLog(abi.getEvent("MilestoneReleased")!,[0,recipient,1000000]);return {address:escrow,topics:e.topics,data:e.data,transactionHash:"0x"+"dd".repeat(32),blockNumber:2,logIndex:0};}
test("config loads deployment metadata from the generated manifest",()=>{const c={CONTRACT_ADDRESS:"not-used",CONTRACT_ABI:"not-used",EVENT_TOPIC_RELEASED:"not-used",EVENT_TOPIC_ARBITRATED:"not-used",EVENT_TOPIC_FORCED:"not-used",EVENT_TOPIC_RECLAIMED:"not-used",GATEWAY_WALLET_ADDRESS:"not-used",GATEWAY_MINTER_ADDRESS:"not-used",DEPLOYMENT_BLOCK:"not-used",ARC_RPC_URL:"http://localhost:1",GATEWAY_API_BASE_URL:"https://gateway-api-testnet.circle.com",RELAYER_PRIVATE_KEY:cfg().relayerPrivateKey};const generated=JSON.parse(readFileSync("config.json","utf8"));const loaded=loadConfig(c);assert.equal(loaded.contractAddress,generated.CONTRACT_ADDRESS);assert.equal(loaded.deploymentBlock,generated.DEPLOYMENT_BLOCK);assert.equal(loaded.gatewayMinterAddress,generated.GATEWAY_MINTER_ADDRESS);assert.throws(()=>loadConfig({...c,RELAYER_PRIVATE_KEY:""}),/RELAYER_PRIVATE_KEY/);});
test("fund event authorizes, submits, and mints one settlement",async()=>{const db=new TransferDatabase(":memory:"),g=new Gateway(),e=new Executor(),r=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await r.initialize();await r.handleLog(log());const row=db.all()[0]!;assert.equal(row.status,"MINTED");assert.equal(row.escrowAddress,escrow);assert.equal(e.auths.length,1);assert.equal(g.requests[0].signature,"0x00");assert.equal(g.requests[0].contractSigner,true);assert.equal(e.mints[0].attestation,"0xabc");r.stop();db.close();});
test("one logical escrow settlement cannot be processed twice from different event identities",async()=>{const db=new TransferDatabase(":memory:"),g=new Gateway(),e=new Executor(),r=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await r.initialize();await r.handleLog(log());const duplicate={...log(),transactionHash:"0x"+"ee".repeat(32),logIndex:9};await r.handleLog(duplicate);assert.equal(db.all().length,1);assert.equal(e.auths.length,1);assert.equal(g.requests.length,1);r.stop();db.close();});
test("database lease excludes concurrent relayer instances",async()=>{const db=new TransferDatabase(":memory:"),g=new BlockingGateway(),e=new Executor(),r1=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100),r2=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await r1.prepare();await r2.prepare();const first=r1.handleLog(log());while(g.requests.length===0)await new Promise<void>(resolve=>setImmediate(resolve));const key=db.all()[0]!.settlementKey;await r2.initiateSettlement(key);assert.equal(g.requests.length,1);assert.equal(e.auths.length,1);g.release();await first;assert.equal(db.get(key)!.status,"MINTED");r1.stop();r2.stop();db.close();});
test("settlement salts are deterministic across relayer restarts",()=>{const first=settlementSalt(escrow,0n);const second=settlementSalt(escrow,0n);const different=settlementSalt(escrow,1n);assert.equal(first,second);assert.notEqual(first,different);});
test("unknown Gateway response without transfer ID requires reconciliation and does not auto-resubmit",async()=>{const db=new TransferDatabase(":memory:"),g=new UnknownThenGateway(),e=new Executor(),first=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await first.initialize();await first.handleLog(log());const pending=db.all()[0]!;assert.equal(pending.status,"RECONCILIATION_REQUIRED");assert.equal(pending.gatewayTransferId,null);const savedIntent=pending.burnIntentJson;first.stop();const restarted=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>1000);await restarted.prepare();await restarted.initiateSettlement(pending.settlementKey);assert.equal(db.get(pending.settlementKey)!.status,"RECONCILIATION_REQUIRED");assert.equal(g.requests.length,1);assert.equal(db.get(pending.settlementKey)!.burnIntentJson,savedIntent);restarted.stop();db.close();});
test("explicitly requeued reconciliation reuses the persisted intent and salt",async()=>{const db=new TransferDatabase(":memory:"),g=new UnknownThenGateway(),e=new Executor(),first=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await first.initialize();await first.handleLog(log());const pending=db.all()[0]!;const savedIntent=pending.burnIntentJson;db.update(pending.settlementKey,{status:"RETRYING",nextRetryAt:100},101);first.stop();const restarted=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>1000);await restarted.initiateSettlement(pending.settlementKey);const recovered=db.get(pending.settlementKey)!;assert.equal(recovered.status,"MINTED");assert.equal(g.requests.length,2);assert.deepEqual(g.requests[0],g.requests[1]);assert.equal(recovered.burnIntentJson,savedIntent);restarted.stop();db.close();});
test("unknown Gateway response with transfer ID queries status without resubmitting",async()=>{const db=new TransferDatabase(":memory:"),g=new ErrorWithTransferIdGateway(),e=new Executor(),first=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await first.initialize();await first.handleLog(log());assert.equal(db.get(db.all()[0]!.settlementKey)!.status,"MINTED");assert.equal(g.requests.length,1);assert.equal(g.getRequests,1);assert.equal(e.auths.length,1);first.stop();db.close();});
test("HTTP 400 with a transfer ID still recovers Gateway status",async()=>{const db=new TransferDatabase(":memory:"),g=new FourHundredWithTransferIdGateway(),e=new Executor(),r=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await r.initialize();await r.handleLog(log());const row=db.all()[0]!;assert.equal(row.status,"MINTED");assert.equal(row.gatewayTransferId,"t-400");assert.equal(g.requests.length,1);assert.equal(g.getRequests,1);r.stop();db.close();});
test("pending Gateway transfer is persisted and reconciled without resubmission",async()=>{const db=new TransferDatabase(":memory:"),g=new PendingThenGateway(),e=new Executor(),r=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await r.initialize();await r.handleLog(log());const row=db.all()[0]!;assert.equal(row.status,"RETRYING");assert.equal(row.gatewayTransferId,"t-pending");assert.equal(g.requests.length,1);await r.initiateSettlement(row.settlementKey);assert.equal(db.get(row.settlementKey)!.status,"MINTED");assert.equal(g.requests.length,1);assert.equal(g.getRequests,2);r.stop();db.close();});
test("known transfer IDs are recovered before retrying a persisted mint",async()=>{const db=new TransferDatabase(":memory:"),g=new Gateway(),e=new Executor();e.failMintOnce=true;const first=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>100);await first.initialize();await first.handleLog(log());const failed=db.all()[0]!;assert.equal(failed.status,"RECONCILIATION_REQUIRED");assert.equal(failed.gatewayTransferId,"t1");first.stop();const restarted=new Relayer(cfg(),db,new Provider(),new Source(),g,e,new Log(),()=>1000);db.update(failed.settlementKey,{status:"MINTING",nextRetryAt:null},1001);await restarted.initiateSettlement(failed.settlementKey);assert.equal(db.get(failed.settlementKey)!.status,"MINTED");assert.equal(g.requests.length,1);assert.equal(g.getRequests,2);restarted.stop();db.close();});
test("HTTP event source polls after the historical cursor and dispatches by topic",async()=>{const provider=new Provider([log()]);const source=new EthersPollingEventSource(provider,cfg(),60_000,500);let received=0;source.subscribe(topics.MilestoneReleased,()=>{received++;});await source.start(1);assert.equal(received,1);source.unsubscribe();});
test("Gateway client sends an unauthenticated array request",async()=>{let seen:any;const server=createServer((req,res)=>{seen={headers:req.headers,method:req.method,url:req.url};let body="";req.on("data",c=>body+=c);req.on("end",()=>{seen.body=JSON.parse(body);res.writeHead(200,{"content-type":"application/json"});res.end("{}");});}).listen(0,"127.0.0.1");await new Promise<void>(resolve=>server.once("listening",()=>resolve()));const port=(server.address() as any).port;const c=new CircleGatewayClient(`http://127.0.0.1:${port}`);await c.submit({burnIntent:{maxBlockHeight:"1",maxFee:"0",spec:{} as any},signature:"0x",contractSigner:true});assert.equal(seen.method,"POST");assert.equal(seen.headers.authorization,undefined);assert.equal(Array.isArray(seen.body),true);server.close();});
