import { Contract, JsonRpcProvider, Interface, type ContractTransactionResponse, type JsonRpcSigner } from "ethers";
import { config } from "./config";
export type Role = "BUYER" | "SELLER" | "ARBITRATOR" | "READ_ONLY";
export type Terms = { buyer: string; seller: string; arbitrator: string; total: bigint; negotiationExpiry: bigint; commitmentWindow: bigint; arbitrationTimeout: bigint; };
export type Milestone = { description: string; basisPoints: bigint; sellerDeadline: bigint; buyerResponseWindow: bigint; disputeWindow: bigint; state: number; documentHash: string; triggerAt: bigint; confirmAt: bigint; disputeAt: bigint; releaseAt: bigint; windowDeadline: bigint; amount: bigint; };
export const readProvider = new JsonRpcProvider(config.rpcUrl);
export const contractFor = (signer?: JsonRpcSigner) => new Contract(config.contractAddress, config.abi, signer || readProvider);
const pick = (value: any, index: number) => value?.[index] ?? value;
export async function readAgreement() { const c = contractFor(); const [state, termsRaw, msRaw, approvals, balances, current] = await Promise.all([c.getState(), c.getTerms(), c.getMilestones(), c.getApprovals(), c.getBalances(), c.getCurrentMilestoneIndex()]); const terms: Terms = { buyer: pick(termsRaw,0), seller: pick(termsRaw,1), arbitrator: pick(termsRaw,2), total: BigInt(pick(termsRaw,4)), negotiationExpiry: BigInt(pick(termsRaw,5)), commitmentWindow: BigInt(pick(termsRaw,6)), arbitrationTimeout: BigInt(pick(termsRaw,7)) }; const milestones: Milestone[] = []; for (let i=0;i<msRaw.length;i++) { const m=msRaw[i]; const s=await c.getMilestoneStatus(i); milestones.push({description:m.description,basisPoints:BigInt(m.basisPoints),sellerDeadline:BigInt(m.sellerDeadline),buyerResponseWindow:BigInt(m.buyerResponseWindow),disputeWindow:BigInt(m.disputeWindow),state:Number(pick(s,0)),documentHash:pick(s,1),triggerAt:BigInt(pick(s,2)),confirmAt:BigInt(pick(s,3)),disputeAt:BigInt(pick(s,4)),releaseAt:BigInt(pick(s,5)),windowDeadline:BigInt(pick(s,6)),amount:BigInt(pick(s,7))}); } return {state:Number(state),terms,milestones,approvals:{buyer:Boolean(pick(approvals,0)),seller:Boolean(pick(approvals,1)),version:Number(pick(approvals,2))},balances:{released:BigInt(pick(balances,0)),remaining:BigInt(pick(balances,1)),disputed:BigInt(pick(balances,2))},current:Number(current)}; }
export function roleFor(address: string, terms: Terms): Role { const a=address.toLowerCase(); if(a===terms.buyer.toLowerCase())return "BUYER"; if(a===terms.seller.toLowerCase())return "SELLER"; if(a===terms.arbitrator.toLowerCase())return "ARBITRATOR"; return "READ_ONLY"; }
export function call(signer: JsonRpcSigner, name: string, ...args: any[]): Promise<ContractTransactionResponse> { return (contractFor(signer) as any)[name](...args); }
export function errorMessage(error: unknown, action?: string): string { const text=String(error).toLowerCase(); if(text.includes("embedded sign-in is not configured")||text.includes("embedded sign-in service is not configured"))return "Sign-in is not configured for this environment. Configure the Circle sign-in bridge and reload."; if(text.includes("deadlinenotreached")||text.includes("deadline not reached"))return "This action isn’t available yet"; if(text.includes("unauthorized")||text.includes("not authorized"))return "This action isn’t available for your account"; if(text.includes("invalidstate")||text.includes("invalidmilestonestate"))return "This has already been completed"; if(action === "approve")return "We couldn’t authorise the payment. Please try again."; if(action === "depositUSDS")return "There was a problem securing the funds. Please try again."; return "Something went wrong. Please try again or contact support."; }
export function eventInterface() { return new Interface(config.abi); }
